### PR TITLE
Fixed mocha module import error #nomergeconfilct

### PR DESCRIPTION
**Pull request by junaid1460**
changed source file structure. Now test files will be kept inside src/test. mocha would read tsconfig.json before test.

### CODE REVIEW

**Comment by kashifmin** [comment]
Tests are still failing for me.

```
> sapien.ml@0.0.1-devl test /home/kashif/Projects/Sapien.ML
> mocha

Error: Cannot find module 'tsconfig-paths/register'
    at Function.Module._resolveFilename (module.js:513:15)
    at Function.Module._load (module.js:463:25)
    at Module.require (module.js:556:17)
    at require (internal/module.js:11:18)
    at /home/kashif/Projects/Sapien.ML/node_modules/mocha/bin/_mocha:366:3
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/home/kashif/Projects/Sapien.ML/node_modules/mocha/bin/_mocha:365:10)
    at Module._compile (module.js:612:30)
    at Object.Module._extensions..js (module.js:623:10)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)
    at Function.Module._load (module.js:486:3)
    at Function.Module.runMain (module.js:653:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

**Comment by kashifmin** [comment]
Btw, I still feel relative imports are necessary. Consider, the code by developer using this libary:

`import { Dense } from 'sapien/core/layers';`

ts compiler will fail to resolve imports inside Dense.ts

`import { Tensor } from 'core/types';`

because it is unaware of the baseUrl, set in tsconfig for sapien.ml source code itself. This will compile fine, but external codes using this library would fail to compile.
I've verified it already and this is what i get:
```
src/core/layers/Dense.ts(1,23): error TS2307: Cannot find module 'core/layers'.
src/core/layers/Dense.ts(2,24): error TS2307: Cannot find module 'core/types'.
src/core/layers/Layer.ts(1,24): error TS2307: Cannot find module 'core/types'
```

**Comment by junaid1460** [comment]
```
➜  Sapien.ML git:(patch4) npm run build;npm run test

> sapien.ml@0.0.1-devl build /home/junaid/code/Sapien.ML
> grunt

Running "ts:default" (ts) task
Compiling...
Cleared fast compile cache for target: default
Using tsc v2.5.3
/home/junaid/code/Sapien.ML/node_modules/typescript/lib/lib.d.ts
/home/junaid/code/Sapien.ML/src/sapien/core/types/Tensor.ts
src/sapien/core/types/index.ts
/home/junaid/code/Sapien.ML/src/sapien/core/layers/Layer.ts
src/sapien/core/layers/index.ts
src/sapien/core/layers/Dense.ts
/home/junaid/code/Sapien.ML/node_modules/mocha-typescript/index.d.ts
src/test/index.test.ts
typings.d.ts
/home/junaid/code/Sapien.ML/node_modules/@types/chai/index.d.ts
/home/junaid/code/Sapien.ML/node_modules/@types/mocha/index.d.ts
/home/junaid/code/Sapien.ML/node_modules/@types/node/inspector.d.ts
/home/junaid/code/Sapien.ML/node_modules/@types/node/index.d.ts


TypeScript compilation complete: 2.83s for 7 TypeScript files.

Running "browserify:dist" (browserify) task
>> Bundle build/sapien.js created.

Running "uglify:build" (uglify) task
>> 1 file created 8.02 kB → 2.62 kB

Done.

> sapien.ml@0.0.1-devl pretest /home/junaid/code/Sapien.ML
> tsc

/home/junaid/code/Sapien.ML/node_modules/typescript/lib/lib.d.ts
/home/junaid/code/Sapien.ML/typings.d.ts
/home/junaid/code/Sapien.ML/src/sapien/core/types/Tensor.ts
/home/junaid/code/Sapien.ML/src/sapien/core/types/index.ts
/home/junaid/code/Sapien.ML/src/sapien/core/layers/Layer.ts
/home/junaid/code/Sapien.ML/src/sapien/core/layers/index.ts
/home/junaid/code/Sapien.ML/src/sapien/core/layers/Dense.ts
/home/junaid/code/Sapien.ML/node_modules/mocha-typescript/index.d.ts
/home/junaid/code/Sapien.ML/src/test/index.test.ts
/home/junaid/code/Sapien.ML/node_modules/@types/chai/index.d.ts
/home/junaid/code/Sapien.ML/node_modules/@types/mocha/index.d.ts
/home/junaid/code/Sapien.ML/node_modules/@types/node/inspector.d.ts
/home/junaid/code/Sapien.ML/node_modules/@types/node/index.d.ts

> sapien.ml@0.0.1-devl test /home/junaid/code/Sapien.ML
> mocha



  Test
created Dense layer
feeding Dense layer
    ✓ testHello


  1 passing (27ms)
```

here it is passing for me

**Comment by junaid1460** [comment]
tsconfig-paths/register not found. probably you should run `npm install`

**Pull request merged**
